title: Rot26 WriteUps
encoding: UTF-8
markdown: kmarkdown
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
#theme: jekyll-theme-midnight
